#ifndef OCTOPART_GLOBAL_H
#define OCTOPART_GLOBAL_H

#if defined(OCTOPART_LIBRARY)
#  define OCTOPART_SHARED_EXPORT Q_DECL_EXPORT
#else
#  define OCTOPART_SHARED_EXPORT Q_DECL_IMPORT
#endif


#endif // OCTOPART_GLOBAL_H
