######################################################################
# Automatically generated by qmake (2.01a) Wed Jan 18 15:19:43 2017
######################################################################

QT += testlib
TEMPLATE = app
TARGET = 
DEPENDPATH += .
DEPENDPATH += ../src
INCLUDEPATH += .
INCLUDEPATH += ../src

# Input
SOURCES += \
  smdresistorcalculator.cpp \
    tests.cpp
  
HEADERS  += smdresistorcalculator.h
  
